config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :doctors
  root to: 'welcome#home'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
    belongs_to :doctor
    belongs_to :user
    
    validates :start, presence: true
    validates :doctor_id, presence: true
    validates :user_id, presence: true
    validates :doctor_id, uniqueness: { scope: :start }
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
    has_many :appointments
    has_many :users, :through => :appointments
    
    validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  
  has_many :appointments
  has_many :doctors, :through => :appointments
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    
    def index
        @appointment = Appointment.all
        @new_appointment = Appointment.new
        @new_appointment.user_id = current_user.id if current_user
        if @new_appointment.save
            redirect_to appointments_show(@appointment)
        else
            render'index'
        end
    end
    
    def destroy 
        @appointment = Appointment.find(params[:id])
        @appointment.destroy
        
        redirect_to appointments_path
    end
    
    def create
        @appointment = Appointment.new
        render plain: params[:appointment].inspect
        @appointment.save
    end
    
    def new
        @appointment = Appointment.new
    end
    
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    
    def show
        @doctor = Doctor.find(params[:id])
    end
    
    def index
        @doctor = Doctor.all
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/create.html.erb
<h2 class="alert">Wybierz termin wizyty</h2>

<div class="formularz-wizyta">
    <%= form_for @appointment do |f| %>
        <%= f.date_select :start %><br/>
        <%= f.time_select :start, {minute_step: 15, start_hour: 7, end_hour: 18}, :ignore_date => false %><br/>
        <%= f.submit "Umów wizytę" %>
    <% end %>
</div>

app/views/appointments/index.html.erb
<section id="sekcja-wizyty">
<% if signed_in? %>
    <!-- Lista wizyt -->
    <div class="wizyty">
        <h3 class="alert">Twoje wizyty</h3>
        <% @appointment.each do |s| %>
                <ul>
                    <% if s.user_id == current_user.id %>
                        <li><div><p>Termin wizyty: <%= s.start %></p>
                        <% if s.start > DateTime.now %>
                            <p><%= button_to 'Odwołaj wizytę', appointment_path(s), method: :delete, data: {confirm: "Czy na pewno chcesz zrezygnować z wizyty?"} %></p></div></li>
                        <% end %>
                    <% end %>
                </ul>
        <% end %>
    </div>
    <!-- Formularz do umawiania wizyty -->
    <div class="formularz-wizyta">
    <h3 class="alert">Umów nową wizytę</h3>
        <%= form_for @new_appointment do |f| %>
            <%= f.date_select :start, {start_year: Date.today.year} %><br/>
            <%= f.time_select :start, {minute_step: 15, start_hour: 7, end_hour: 18}, :ignore_date => false %><br/>
            <%= f.collection_select(:doctor_id, Doctor.all, :id, :name ) %><br/>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.submit "Umów wizytę" %>
        <% end %>
    </div>
<% else %>
    <h2 class="alert">Zaloguj się, aby zobaczyć swoje wizyty</h2>
    <%= render partial: 'sessions/form' %>
<% end %>
</section>



<footer>
  <div class="contact-data">
    <h2>Lorem Med inc.</h2>
    <div class="address">Ipsum City<br>
    Dolor Ave. 5 <br/>
    10392 California
    
  </div>
    
    
  </div>
  <div class="contact-form">
    <form>
        <input type="text" id="name" placeholder="Imię i nazwisko"><br/>
        <input type="email" id="email" placeholder="E-mail"><br/>
        <input type="textarea" id="message" placeholder="Wiadomość"><br/>
        <input type="submit">
    </form>
  </div>
</footer>

app/views/doctors/index.html.erb
<% if signed_in? %>
<div><h2 class="alert" align="center">Poznaj nasz wspaniały zespół!</h2></div>
    <div class="team-container">
    <% @doctor.each do |s| %>
        <div class="lekarz">
            <h3><%= s.name %> - <%= s.specialization %></h3><br/>
            <%= s.info %>
            <%= button_to 'Pokaż profil', doctor_path(s.id) %>
        </div>
    <% end %>
    </div>
<% else %>
    <h2 class="alert">Zaloguj się by wyświetlić lekarzy</h2>
    <%= render '/sessions/form' %>
<% end %>



<footer>
  <div class="contact-data">
    <h2>Lorem Med inc.</h2>
    <div class="address">Ipsum City<br>
    Dolor Ave. 5 <br/>
    10392 California
    
  </div>
    
    
  </div>
  <div class="contact-form">
    <form>
        <input type="text" id="name" placeholder="Imię i nazwisko"><br/>
        <input type="email" id="email" placeholder="E-mail"><br/>
        <input type="textarea" id="message" placeholder="Wiadomość"><br/>
        <input type="submit">
    </form>
  </div>
</footer>

app/views/doctors/show.html.erb
<h1>Doctor <%= @doctor.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <h1>Lorem Med</h1>
  <h2>We'll ipsum your disease</h2>
</header>

<nav>
  <ul id="nav-left">
   <li><%= link_to 'Strona Główna', root_path %></li>
   <li><%= link_to 'Twoje wizyty', appointments_path %></li>
   <li><%= link_to 'Nasz zespół', doctors_path %></li>
  </ul>
  <section id="nav-right">
    <% if signed_in? %>
      <div class="signed-box"><p>Signed in as: <%= current_user.email %></p></div>
      <div class="signed-box"><%= button_to 'Sign out', sign_out_path, method: :delete %></div>
    <% else %>
      <div class="signed-box"><%= link_to 'Sign in', sign_in_path %></div>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
</section>
</nav>


<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/welcome/home.html.erb
<section id="about">
    <h2 class="alert">Lorem Med</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
    magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo 
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
</section>


<footer>
  <div class="contact-data">
    <h2>Lorem Med inc.</h2>
    <div class="address">Ipsum City<br>
    Dolor Ave. 5 <br/>
    10392 California
    
  </div>
    
    
  </div>
  <div class="contact-form">
    <form>
        <input type="text" id="name" placeholder="Imię i nazwisko"><br/>
        <input type="email" id="email" placeholder="E-mail"><br/>
        <input type="textarea" id="message" placeholder="Wiadomość"><br/>
        <input type="submit">
    </form>
  </div>
</footer>